<a href="https://colab.research.google.com/github/hyerimson/August_Coding/blob/main/230809_%EB%A9%80%ED%8B%B0%EC%BA%A0%EC%B7%A8%EC%97%85%EC%BA%A0%ED%94%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Streamlit
1. streamlit이 설치된 가상환경으로 진입힌다.
2. app.py 파일이 있는 폴더로 이동한다.
3. streamlit run app.py 명령어로 웹서버를 작동시킨다.

### streamlit 웹서버 종료 방법
    - streamlit을 실행시킨터미널(콘솔, powershell prompt)에서
    
    crtl + c 버튼을 누른다.

- 8502는 포트번호

### streamlit 웹서버는 app.py 파일에 있는 내용을 실행시켜 웹브라우저에 표출해준다.

### app.py 파일에는 streamlit에서 제공하는 명령어들을 사용하여 원하는 내용을 웹브라우저에 표출시킬 수 있다.

### streamlit에서 웹브라우저에 뭔가를 표시하기 위해서는 streamlit 명령어를 사용해야 한다.

* streamlit 명령어는 파이썬기본 문법을사용할 수 있다.
* 파이썬 코드들을 수용할 수 있다.

---
<최소한 알고있으면 좋은 streamlit 명령어>
- st.dataframe
 - 데이터 프레임을 대화형 테이블로 표시
      
        st.dataframe(data=None, width=None, height=None, *,
        use_container_width=False,
        hide_index=None,
        column_order=None,
        column_config=None)
 - 예시
        import streamlit as st
        import pandas as pd
        import numpy as np

        df = pd.DataFrame(
        np.random.randn(50, 20),
        columns=('col %d' % i for i in range(20)))

        st.dataframe(df)  # Same as st.write(df)

- st.pyplot
 - matplotlib.pyplot 그림을 표시
        st.pyplot(fig=None,
        clear_figure=None,
        use_container_width=True, **kwargs)
 - 예시
        arr = np.random.normal(1, 1, size=100)
        fig, ax = plt.subplots()
        ax.hist(arr, bins=20)

        st.pyplot(fig)

- st.button
 - 버튼 위젯을 표시
        st.button(label, key=None,
        help=None, on_click=None, args=None,
        kwargs=None, *, type="secondary",
        disabled=False,
        use_container_width=False)
 - 예시
        import streamlit as st

        if st.button('Say hello'):
            st.write('Why hello there')
        else:
            st.write('Goodbye')

- st.text_input
 - 텍스트 데이터를 입력하고 싶은 경우
        st.text_input(label, value="",
        max_chars=None, key=None,
        type="default", help=None,
        autocomplete=None, on_change=None,
        args=None, kwargs=None, *,
        placeholder=None, disabled=False,
        label_visibility="visible")
 - 예시
        title = st.text_input('Movie title', 'Life of Brian')
        
        st.write('The current movie title is', title)

- st.header/title/write
 - title : 제목 형식으로 텍스트를 표시
        st.title('This is a title')
        st.title('A title with _italics_ :blue[colors] and emojis :sunglasses:')
 - header : 헤더 형식으로 텍스트를 표시
        st.header('This is a header')
        st.header('A header with _italics_ :blue[colors] and emojis :sunglasses:')
 - write : 인수 쓰기
        st.write('Hello, *World!* :sunglasses:')

- streamlit_folium 라이브러리의 folium_static 사용

- http://192.249.19.109/ 참고 사이트
- https://zzsza.github.io/mlops/2021/02/07/python-streamlit-dashboard/ Streamlit 사용법 사이트

In [10]:
import requests
from datetime import datetime as date
import json
import pandas as pd

In [3]:
url = 'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=c3a0fa760324363ef7cde2afa0d73297&targetDt='

In [7]:
resp = requests.get(url+'20230807')

In [8]:
data = resp.json()['boxOfficeResult']['dailyBoxOfficeList']

In [ ]:
data

In [12]:
dataframe_of_movie = pd.DataFrame(data)
dataframe_of_movie

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt
0,1,1,0,OLD,20218541,밀수,2023-07-26,1232648801,42.2,-2166756628,-63.7,35399158442,132285,-211805,-61.6,3667878,1462,5905
1,2,2,0,OLD,20193879,비공식작전,2023-08-02,555928175,19.0,-1073439752,-65.9,7335665598,59432,-104646,-63.8,759613,1042,3788
2,3,3,0,OLD,20228930,엘리멘탈,2023-06-14,386875002,13.2,-673339635,-63.5,62469053639,41064,-65217,-61.4,6354883,849,2546
3,4,4,0,OLD,20218935,더 문,2023-08-02,227943879,7.8,-444413708,-66.1,3957795255,23854,-39539,-62.4,384791,812,2390
4,5,5,0,OLD,20232631,미션 임파서블: 데드 레코닝 PART ONE,2023-07-12,182954660,6.3,-275307774,-60.1,38909499332,19236,-26755,-58.2,3866601,576,1134
5,6,6,0,NEW,20226500,달짝지근해: 7510,2023-08-15,59329000,2.0,59329000,100,59329000,6637,6637,100,6637,30,30
6,7,7,0,OLD,20232536,명탐정코난: 흑철의 어영,2023-07-20,63667934,2.2,-67993554,-51.6,6546221149,6502,-6487,-49.9,685441,292,406
7,8,8,0,OLD,20232740,바비,2023-07-19,63838454,2.2,-59546699,-48.3,5127620815,6360,-5074,-44.4,524532,213,348
8,9,9,-3,OLD,20232836,몬스터 패밀리 2,2023-08-02,31666643,1.1,-90359347,-74,629403510,3586,-9637,-72.9,70629,348,491
9,10,10,-1,OLD,20219331,여름날 우리,2021-08-25,19031624,0.7,-23591582,-55.3,3838987333,2247,-2879,-56.2,395685,111,149

In [13]:
df = dataframe_of_movie.loc[:, ['rank','movieNm','openDt','salesAmt']]
df

  rank                   movieNm      openDt    salesAmt
0    1                        밀수  2023-07-26  1232648801
1    2                     비공식작전  2023-08-02   555928175
2    3                      엘리멘탈  2023-06-14   386875002
3    4                       더 문  2023-08-02   227943879
4    5  미션 임파서블: 데드 레코닝 PART ONE  2023-07-12   182954660
5    6               달짝지근해: 7510  2023-08-15    59329000
6    7             명탐정코난: 흑철의 어영  2023-07-20    63667934
7    8                        바비  2023-07-19    63838454
8    9                 몬스터 패밀리 2  2023-08-02    31666643
9   10                    여름날 우리  2021-08-25    19031624

app.py : 웹서버를 리스닝(계속 지켜본다)하며, 페이지 변경 요청이 있을 때, 페이지 구분을 해준다.

page 폴더의 파일들 : app.py로부터 호출을 받아서 클라이언트 역할을 하며, utils 폴더에 작성되는 모듈로부터 함수를 호출한다.

utils 폴더의 파일들 : page 폴더에 있는 파일들의 모듈로써, 파이썬 코드로만 작성된 경우가 대부분이며 실제 코드를 작성해야 하는 부분이다.

app - page 폴더 파일 (클라이언트 - 모듈)

page 폴더 파일 - utils 폴더 파일 (클라이언트 - 모듈)